### ISSUE TITLE
wireframe the dashboard - app overview

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/dashboard#10]
**The dashboard main role as a MVP is to provide a cohesive UI to create or manage apps and teams. As we want to iterate fast, we need a stable and approved architecture**

We need an app management subroute that will be the entrypoint of the whole app overview and management. For now, we want to display the overview of the app; its `name` and the attached `environment`, its `current release`, its `story payload`, its `source` and the release `status`.

- [x] overview when no releases are there (Fixes #51 #74)
- [x] topbar component (Fixes #52)
- [x] overview page with basic informations
- [x] add app graphQL data in the routes (Fixes #65)

Fixes #51 #52 #65 #74
